### ISSUE TITLE
Invoice titles are incomplete

### ISSUE THREAD

**Issue by avillegasn** [wceu/camptix-invoices#10]
Invoice title for those invoices that are automatically generated use the following format: 

`Invoice #X for order #Y on Z`

* where X is the invoice number,
* Y is the transaction ID,
* Z is the date where the `attendee` is created

Note that the value of the transaction ID is not properly retrieved (appears empty). We should fix that or even choose a different (more human-friendly) format for the title which includes the email of the attendee (e.g. `Invoice #X for {email} on Z`).

**Comment by iceablemedia** [comment]
The transaction ID is properly retrieved and included in the invoice title on my end (local VVV site, ticket "paid" with Paypal Sandbox).

How - with what config / payment method - did you get this issue?

Something more human friendly anyway, like the email address, sounds good.

I would still want to fix this issue and make sure the transaction ID is always retrieved properly and stored as post meta.
(Edit: transaction ID is now stored as post meta since https://github.com/wceu/camptix-invoices/commit/cbcce56e95c50142304f8546092e0927ce7e8c88 - we still need to troubleshoot your issue with the transaction ID not being retrieved)

We could even include it in the invoice itself (e.g. "Paid via Paypal ; Transaction ID: XXXXXX")

**Comment by avillegasn** [comment]
When I use a 100% discount coupon, the transaction ID is null in the database (the postmeta transaction_id appears, but with a null value). Maybe that's the only scenario where this happens. I'll explore this a little bit more...

**Comment by avillegasn** [comment]
Now titles follow this format:

`Invoice #{invoice-number} for {attendee-email} (order #{transaction-id}) on {purchase date}`

When using a 100% discount coupon code, no transaction occurs. In that case, the title is the same but without the `(order #{transaction-id})` fragment.

Commit 02f34d6 fixes this issue.
