### ISSUE TITLE
[Blocker] Specify expected logo image size and supported format somewhere.

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#25]
Hopefully its a small fix. Please add a messaging in the settings menu which specifies what should be the expected size of the logo image for it to be rendered properly.

**Comment by iandunn** [comment]
I wonder if we can automate this using something similar to `WordCamp\Jetpack_Tweaks\default_single_og_image()` ?

https://github.com/WordPress/wordcamp.org/blob/39edd326e258775026d4e935085da9ad30616539/public_html/wp-content/mu-plugins/jetpack-tweaks/sharing.php#L39-L45

We have a default image for those that don't provide one:

https://github.com/WordPress/wordcamp.org/blob/39edd326e258775026d4e935085da9ad30616539/public_html/wp-content/mu-plugins/jetpack-tweaks/sharing.php#L39-L45

Although that and the header image might not match the dimensions we want.

A simpler option might be to just always hardcode the WordPress logo, instead of making it specific to an individual camp.

**Comment by iceablemedia** [comment]
WCEU currently uses the WordPress Community Support logo for invoices, and I wouldn't be surprised if this was the case for many other WordCamps.

Using this by default when the plugin runs on wordcamp.org sounds good.

On other sites, we could leave this setting empty by default since a logo is not required to produce an invoice.
