### ISSUE TITLE
Fields are empty when invoices are generated directly

### ISSUE THREAD

**Issue by vedanshujain** [wceu/camptix-invoices#30]
In generated PDF file, fields are empty (customer name, email etc) when adding new invoice directly, unless invoice post is saved to a draft first.

**Comment by avillegasn** [comment]
That was true. I had to fix the way invoice documents where generated. Now they are only generated when the invoice is published and has the required fields. In addition to it, when passing a published invoice to draft, its associated PDF is deleted (and regenerated when you publish again the invoice).

Fixed in 89d15cd498a328bc06f93765d53e0b22ea029307
