### ISSUE TITLE
Question: Why an API endpoint for the invoice form fields?

### ISSUE THREAD

**Issue by coreymckrill** [wceu/camptix-invoices#33]
The "I need an invoice" toggle checkbox and the related form fields are getting added to the ticket purchase form by asynchronously loading the HTML markup from a custom REST API endpoint and appending it to the form using jQuery.

What was the reason for doing it like this instead of adding an action to the `camptix_attendee_form_after_questions` hook?

**Comment by avillegasn** [comment]
The way to append the invoice request related form fields via REST API endpoint is something that the original plugin already had.

I've tried to use the `camptix_attendee_form_after_questions` hook, but this is located after every attendee. Note that an order may have several attendees. Placing the form fields there, we'll add the fields several times. We just want these fields to be placed once inside the form.

There is another hook called `camptix_form_attendee_info_before`, but adding the fields there does not work because the fields are outside the Camptix form. The Camptix form is constructed using `ob_start()`...

It seems no hook exists for the purpose we want. That would explain why the original developers had to do this ugly hack to put the form fields in place.

If you guys add a hook after line 5626 of camptix.php, I'll change the REST API hack in Camptix Invoices plugin. Otherwise, I believe I'm not able to fix this.

**Comment by coreymckrill** [comment]
> Placing the form fields there, we'll add the fields several times. We just want these fields to be placed once inside the form.

Oh, good point. I will look into adding an appropriate action hook.

**Comment by coreymckrill** [comment]
Ok, I've added two new action hooks that could be used for outputting this form. Details here:

https://github.com/Automattic/camptix/commit/96cabdbb5f9a2199297dc91c0fd3dccd01c7d416

**Comment by avillegasn** [comment]
Thanks for the hook @coreymckrill. We don't use the weird REST API hack anymore and now insert the invoice request fields properly.

Then I close the issue.
